org: lucasbrogni
app: prospects-api
service: prospects-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    PROSPECT_COLLECTION: prospects
    PROSPECT_STATS_COLLECTIONS: prospectsStats
    DB_NAME: prospects
    DB_URL: mongodb+srv://prospects:any@lucasbrogni.zch9p.mongodb.net

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true


package:
  exclude:
    - config/.env.stg
    - config/.env.pro
    - coverage/**
    - .circleci/**

  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: prospects
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: prospects/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: prospects
          method: get
          caching:
            enabled: true
            
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: prospects/{id}
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: prospects/{id}
          method: delete

  disable: 
    handler: app/handler.disable
    events:
      - http:
          path: prospects/{id}/disable
          method: put
  
  enable: 
    handler: app/handler.enable
    events:
      - http:
          path: prospects/{id}/enable
          method: put

  createStatsProspects: 
    handler: app/handler.createStats
    events:
      - http:
          path: prospects/{id}/stats
          method: post
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id

  findStatsByProspect: 
    handler: app/handler.findStatsByProspect
    events:
      - http:
          path: prospects/{id}/stats
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id

  compareProspectsByStats: 
    handler: app/handler.compareProspectsByStats
    events:
      - http:
          path: prospects/{id}/relateds
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id

  createProspectCombineInfo: 
    handler: app/handler.createProspectCombineInfo
    events:
      - http:
          path: prospects/{id}/combine
          method: post
          
  findCombineDataByProspect: 
    handler: app/handler.findCombineDataByProspect
    events:
      - http:
          path: prospects/{id}/combine
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id
  
  findCombineData: 
    handler: app/handler.findCombineData
    events:
      - http:
          path: prospects/combine
          method: get

