org: lucasbrogni
app: prospects-api
service: prospects-api

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 2 # optional, in seconds, default is 6
  provisionedConcurrency: 10
  environment:
    NODE_ENV: dev
    PROSPECT_COLLECTION: prospects
    PROSPECT_STATS_COLLECTIONS: prospectsStats
    DB_NAME: prospects
    DB_URL: mongodb+srv://prospects:any@lucasbrogni.zch9p.mongodb.net
    JWT_SECRET: +QueSecreto
    SECRET_ADM_MAKER: JamalAdams#Prez

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: false

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
    - coverage/**
    - .circleci/**

  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: prospects
          method: post
          authorizer: authorizerFunc 
          cors:
            origin: '*'
  
  update:
    handler: app/handler.update
    events:
      - http:
          path: prospects/{id}
          method: put
          cors:
            origin: '*'
  find:
    handler: app/handler.find
    events:
      - http:
          path: prospects
          method: get
          caching:
            enabled: false
          cors:
            origin: '*'
            
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: prospects/{id}
          method: get
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
          cors:
            origin: '*'

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: prospects/{id}
          method: delete
          authorizer: authorizerFunc
          cors:
            origin: '*'

  disable: 
    handler: app/handler.disable
    events:
      - http:
          path: prospects/{id}/disable
          method: put
          authorizer: authorizerFunc
          cors:
            origin: '*'
  
  enable: 
    handler: app/handler.enable
    events:
      - http:
          path: prospects/{id}/enable
          method: put
          authorizer: authorizerFunc
          cors:
            origin: '*'

  createStatsProspects: 
    handler: app/handler.createStats
    events:
      - http:
          path: prospects/{id}/stats
          method: post
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
          authorizer: authorizerFunc
          cors:
            origin: '*'

  updateStatsProspect: 
    handler: app/handler.updateStats
    events: 
      - http: 
          path: prospects/{id}/stats
          method: put
          authorizer: authorizerFunc
          cors:
            origin: '*'

  findStatsByProspect: 
    handler: app/handler.findStatsByProspect
    events:
      - http:
          path: prospects/{id}/stats
          method: get
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
          cors:
            origin: '*'

  compareProspectsByStats: 
    handler: app/handler.compareProspectsByStats
    events:
      - http:
          path: prospects/{id}/relateds
          method: get
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
          cors:
            origin: '*'

  createProspectCombineInfo: 
    handler: app/handler.createProspectCombineInfo
    events:
      - http:
          path: prospects/{id}/combine
          method: post
          authorizer: authorizerFunc
          cors:
            origin: '*'
          
  findCombineDataByProspect: 
    handler: app/handler.findCombineDataByProspect
    events:
      - http:
          path: prospects/{id}/combine
          method: get
          caching:
            enabled: false
            cacheKeyParameters:
              - name: request.path.id
          cors:
            origin: '*'
  
  findCombineData: 
    handler: app/handler.findCombineData
    events:
      - http:
          path: prospects/combine
          method: get
          cors:
            origin: '*'

  updateCombineData: 
    handler: app/handler.updateCombineData
    events:
      - http:
          path: prospects/{id}/combine
          method: put
          authorizer: authorizerFunc
          cors:
            origin: '*'
  
  deleteCombineData: 
    handler: app/handler.deleteCombineData
    events:
      - http:
          path: prospects/{id}/combine
          method: delete
          authorizer: authorizerFunc
          cors:
            origin: '*'

  createUser: 
    handler: app/handler.createUser
    events:
      - http:
          path: users
          method: post
          cors:
            origin: '*'

  evaluateProspect: 
    handler: app/handler.evaluateProspect
    events:
      - http:
          path: prospects/{id}/evaluations
          method: post
          authorizer: authorizerFunc
          cors:
            origin: '*'

  findUserProspectEvaluations: 
    handler: app/handler.findUserProspectEvaluations
    events:
      - http:
          path: prospects/{id}/user/evaluations
          method: get
          authorizer: authorizerFunc
          cors:
            origin: '*'
  
  removeProspectEvaluation: 
    handler: app/handler.removeProspectEvaluation
    events:
      - http:
          path: prospects/{id}/evaluations
          method: delete
          authorizer: authorizerFunc
          cors:
            origin: '*'
  
  findProspectEvaluations: 
    handler: app/handler.findProspectEvaluations
    events:
      - http:
          path: prospects/{id}/evaluations
          method: get
          cors:
            origin: '*'

  updateProspectEvaluation: 
    handler: app/handler.updateProspectEvaluation
    events:
      - http:
          path: prospects/{id}/evaluations
          method: patch
          authorizer: authorizerFunc
          cors:
            origin: '*'

  login: 
    handler: app/handler.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: '*'
  
  makeUserAdm: 
    handler: app/handler.makeAdm
    events:
      - http:
          path: users/makeAdm
          method: post
          cors:
            origin: '*'

  authorizerFunc:
    handler: app/handler.authorizerFunc

