jobs:
  build:
    working_directory: ~/prospects-api

    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      
      - run:
          name: Update node to v14.16.0
          shell: /bin/sh
          command: nvm install v14.16.0

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run:
          name: Run tests with code coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: sls deploy

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
